root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/gateway ./cmd/gateway"
  bin = "./tmp/gateway"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
