-- ============================================================
-- SEED: Questions with fixed OptionsJson
-- Generated: 2026-06-24T08:28:27.408Z
-- Total: 160
-- ============================================================

USE [ToeicVocabularyPlatform]
GO

PRINT 'Seeding Questions with OptionsJson fixes...'
GO

UPDATE [dbo].[Questions] SET OptionsJson = N'["việc tiếp tục xử lý, theo dõi sau đó","Bảo trì, duy trì","Tài sản","Sự đặt chỗ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 21;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 22;
UPDATE [dbo].[Questions] SET OptionsJson = N'["ví dụ","Cấu hình","Mục tiêu","Bài giảng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 23;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 24;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Tài liệu tham khảo","Giờ đi ngủ","chuong trinh nghi su, noi dung cuoc hop","Khoa, đội ngũ giảng viên"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 31;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 32;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Tài sản","cuoc hen, lich hen","Bản thảo, dự thảo","đề xuất, bản đề xuất"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 33;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 34;
UPDATE [dbo].[Questions] SET OptionsJson = N'["cộng tác, hợp tác","xác nhận","ăn","sap xep, bo tri"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 35;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 36;
UPDATE [dbo].[Questions] SET OptionsJson = N'["tham du, co mat","Lưu hành, phổ biến","Thúc đẩy, xúc tiến","dời lịch, sắp xếp lại lịch"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 37;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 38;
UPDATE [dbo].[Questions] SET OptionsJson = N'["ngan gon; thong bao tom tat","tóm tắt","Bữa sáng","Chương trình giảng dạy"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 39;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 40;
UPDATE [dbo].[Questions] SET OptionsJson = N'["ăn","Đàm phán","Đăng ký học","cong tac, hop tac"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 41;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 42;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Thư giãn","xac nhan","giao phó, ủy quyền","ăn"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 43;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 44;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Tường lửa","han chot","Lợi nhuận","Máy chủ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 45;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 46;
UPDATE [dbo].[Questions] SET OptionsJson = N'["cộng tác, hợp tác","Đăng ký học","Thức dậy","giao pho, uy quyen"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 47;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 48;
UPDATE [dbo].[Questions] SET OptionsJson = N'["dời lịch, sắp xếp lại lịch","ăn","thao luan","Lưu hành, phổ biến"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 49;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 50;
UPDATE [dbo].[Questions] SET OptionsJson = N'["đề xuất, bản đề xuất","Nhà ga","su gia han, may nhanh noi bo","Bài giảng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 51;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 52;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Hải quan","Bản thảo, dự thảo","viec tiep tuc xu ly, theo doi sau do","Trụ sở chính"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 53;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 54;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Học bổng","Chương trình giảng dạy","Giao diện","bien ban cuoc hop"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 55;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 56;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Đăng ký học","tri hoan","Thúc đẩy, xúc tiến","Đi lại hàng ngày"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 57;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 58;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Doanh thu","de xuat, ban de xuat","Hợp đồng","Việc giặt giũ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 59;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 60;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Giờ nghỉ, giải lao","Bảo trì, Duy trì","ve viec, lien quan den","Hàng tạp hóa"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 61;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 62;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Lưu hành, phổ biến","tóm tắt","doi lich, sap xep lai lich","giao phó, ủy quyền"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 63;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 64;
UPDATE [dbo].[Questions] SET OptionsJson = N'["sắp xếp, bố trí","tom tat","Thức dậy","Tải xuống"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 65;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 66;
UPDATE [dbo].[Questions] SET OptionsJson = N'["dia diem to chuc","Luận án","Nghiên cứu","Hợp đồng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 67;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 68;
UPDATE [dbo].[Questions] SET OptionsJson = N'["quy trinh lam viec","Làm thủ tục","Lợi nhuận","hạn chót"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 69;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 70;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Tài liệu tham khảo","Vệ sinh","Chiến lược","Làm thủ tục"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 71;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 72;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Doanh thu","sự gia hạn, máy nhánh nội bộ","ví dụ","Nghiên cứu"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 73;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 74;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Ước tính","Mua hàng","trì hoãn","Đàm phán"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 75;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 76;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Học bổng","Hiệu quả","ngắn gọn; thông báo tóm tắt","Thư giãn"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 77;
UPDATE [dbo].[Questions] SET OptionsJson = N'["thảo luận","Lưu hành, phổ biến","cộng tác, hợp tác","Đàm phán"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 78;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Thúc đẩy","Ăn quá nhiều","Trì hoãn","Lưu hành, phổ biến"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 79;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Phê duyệt","Ước tính","cộng tác, hợp tác","Tốt nghiệp"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 80;
UPDATE [dbo].[Questions] SET OptionsJson = N'["thảo luận","Đi lại hàng ngày","Thư giãn","Mua hàng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 81;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cài đặt","Thức dậy","Cập nhật","tham dự, có mặt"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 82;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 83;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Học kỳ","Bài giảng","Bữa sáng","đề xuất, bản đề xuất"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 84;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Đi lại hàng ngày","thảo luận","Thư giãn","Mua hàng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 85;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Hàng tạp hóa","Đề cương môn học","Bữa sáng","Học kỳ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 86;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Giao lưu","Tải xuống","Tập thể dục","ăn"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 87;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Thư giãn","tham dự, có mặt","Cập nhật","Trì hoãn"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 88;
UPDATE [dbo].[Questions] SET OptionsJson = N'["sự gia hạn, máy nhánh nội bộ","đề xuất, bản đề xuất","Thời gian rảnh","Bài giảng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 89;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Thuộc gia đình","thảo luận","Ngân sách","việc tiếp tục xử lý, theo dõi sau đó"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 90;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Bài tập","Việc giặt giũ","Nghiên cứu","Bữa sáng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 91;
UPDATE [dbo].[Questions] SET OptionsJson = N'["giao phó, ủy quyền","Giao lưu","trì hoãn","sắp xếp, bố trí"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 92;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Sự khởi hành","Học kỳ","Học bổng","Bản thảo, dự thảo"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 93;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 94;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Bài giảng","Hành lý","Mục tiêu","Hợp đồng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 95;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Tài liệu tham khảo","Doanh thu","Sự đặt chỗ","ví dụ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 96;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cập nhật","ăn","sắp xếp, bố trí","Trì hoãn"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 97;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Hải quan","sự gia hạn, máy nhánh nội bộ","Lịch trình","việc tiếp tục xử lý, theo dõi sau đó"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 98;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Lịch trình","Hải quan","hạn chót","Thời gian rảnh"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 99;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cơ sở dữ liệu","Làm thủ tục","Mã hóa","Ngân sách"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 100;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 101;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Giao thức","Quá cảnh","Chuyến bay đêm","Nhà ga"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 102;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Sự đến nơi","sự gia hạn, máy nhánh nội bộ","Bảo trì, Duy trì","Mục tiêu"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 103;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Bảo trì, Duy trì","Phần mềm","Việc giặt giũ","Quá cảnh"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 104;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 105;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Điểm đến","Hành lý","Sự đến nơi","Cơ sở dữ liệu"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 106;
UPDATE [dbo].[Questions] SET OptionsJson = N'["trì hoãn","Cập nhật","dời lịch, sắp xếp lại lịch","Ước tính"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 107;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 108;
UPDATE [dbo].[Questions] SET OptionsJson = N'["hạn chót","Tài sản","Mạng lưới","Bài tập"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 109;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Tải xuống","Mua hàng","Đàm phán","thảo luận"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 110;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 111;
UPDATE [dbo].[Questions] SET OptionsJson = N'["đề xuất, bản đề xuất","Sao lưu","Giao diện","Nhà ga"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 112;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cài đặt","cộng tác, hợp tác","Ước tính","tham dự, có mặt"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 113;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 114;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cấu hình","Lợi nhuận","việc tiếp tục xử lý, theo dõi sau đó","Bằng cấp"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 115;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Mục tiêu","Nghiên cứu","Sự đến nơi","chương trình nghị sự, nội dung cuộc họp"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 116;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 117;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Sao lưu","Sự khởi hành","Giờ đi ngủ","Bài tập"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 118;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cấu hình","quy trình làm việc","Bảo trì, Duy trì","Bài giảng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 119;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 120;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Học phí","Học bổng","Mã hóa","Tài liệu tham khảo"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 121;
UPDATE [dbo].[Questions] SET OptionsJson = N'["thảo luận","Đăng ký học","Đàm phán","xác nhận"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 122;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cập nhật","Thư giãn","Tốt nghiệp","sắp xếp, bố trí"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 123;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Học phí","Nghị quyết, giải pháp","Chương trình giảng dạy","chương trình nghị sự, nội dung cuộc họp"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 124;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Học phí","Giao thức","Việc vặt, việc nhà","biên bản cuộc họp"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 125;
UPDATE [dbo].[Questions] SET OptionsJson = N'["biên bản cuộc họp","Tài sản","Tài liệu tham khảo","Hành lý"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 126;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Tài sản","Tường lửa","Việc vặt, việc nhà","Đầu tư"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 131;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 132;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Giao diện","Mạng lưới","Ngân sách","Giao thức"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 133;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 134;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Làm thủ tục","Hợp đồng","Giao diện","Bài tập"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 135;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 136;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Đầu tư","Đề cương môn học","Cơ sở dữ liệu","Sao lưu"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 137;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 138;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Trụ sở chính","Chương trình giảng dạy","Hành lý","Lợi nhuận"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 139;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 140;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Lưu hành, phổ biến","Ăn quá nhiều","Thúc đẩy, xúc tiến","giao phó, ủy quyền"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 141;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 142;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Bài tập","Hợp đồng","Học kỳ","Bản thảo, dự thảo"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 143;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 144;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Chương trình giảng dạy","Trụ sở chính","Học kỳ","Sự đến nơi"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 145;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 146;
UPDATE [dbo].[Questions] SET OptionsJson = N'["tóm tắt","cộng tác, hợp tác","giao phó, ủy quyền","Thuê ngoài"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 147;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 148;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Nghị quyết, giải pháp","Luận án","Giao diện","Hành lý"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 149;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 150;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cấu hình","Thời gian rảnh","Học bổng","Vệ sinh"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 151;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 152;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Đầu tư","Ngân sách","Việc vặt, việc nhà","cuộc hẹn, lịch hẹn"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 153;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 154;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Bảo trì, Duy trì","Cấu hình","Giờ nghỉ, giải lao","ví dụ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 155;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 156;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Chương trình giảng dạy","Giờ đi ngủ","Chuyến bay đêm","Việc vặt, việc nhà"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 157;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 158;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Ăn quá nhiều","Giao lưu","Thuê ngoài","Tải xuống"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 159;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 160;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Sự khởi hành","Việc vặt, việc nhà","biên bản cuộc họp","Hành lý"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 161;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 162;
UPDATE [dbo].[Questions] SET OptionsJson = N'["biên bản cuộc họp","Lên máy bay","Tường lửa","Nhà ga"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 163;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 164;
UPDATE [dbo].[Questions] SET OptionsJson = N'["biên bản cuộc họp","Giao thức","Quá cảnh","Lên máy bay"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 165;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 166;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Lịch trình","Giao diện","Điểm đến","Cấu hình"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 167;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 168;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Chuyến bay đêm","Tài liệu tham khảo","Cấu hình","Bản thảo, dự thảo"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 169;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 170;
UPDATE [dbo].[Questions] SET OptionsJson = N'["sự gia hạn, máy nhánh nội bộ","việc tiếp tục xử lý, theo dõi sau đó","Máy chủ","Học kỳ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 171;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 172;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Mục tiêu","Bảo trì, Duy trì","Tường lửa","Sự khởi hành"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 173;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 174;
UPDATE [dbo].[Questions] SET OptionsJson = N'["địa điểm tổ chức","Cơ sở dữ liệu","Mã hóa","Học bổng"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 175;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 176;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Thời gian rảnh","Giao diện","Giao thức","Bản thảo, dự thảo"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 177;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 178;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Cơ sở dữ liệu","Giao diện","Chuyến bay đêm","Bảo trì, Duy trì"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 179;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 180;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Doanh thu","đề xuất, bản đề xuất","Bằng cấp","biên bản cuộc họp"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 181;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 182;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Hành lý","Cấu hình","Nghiên cứu","Học kỳ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 183;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 184;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Trụ sở chính","Bài giảng","Đề cương môn học","Luận án"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 185;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 186;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Khoa, đội ngũ giảng viên","cuộc hẹn, lịch hẹn","Chuyến bay đêm","ví dụ"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 187;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 188;
UPDATE [dbo].[Questions] SET OptionsJson = N'["Chương trình giảng dạy","Sự đặt chỗ","Luận án","cuộc hẹn, lịch hẹn"]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 189;
UPDATE [dbo].[Questions] SET OptionsJson = N'[]', UpdatedAt = SYSDATETIMEOFFSET() WHERE QuestionID = 190;

PRINT 'Updated 160 questions with realistic OptionsJson.';
GO
